version: "3"

tasks:
  dock:
    desc: Change Dock Settings
    cmds:
      // デフォルトアプリをDockから除去
      - defaults write com.apple.dock persistent-apps -array
      // 起動中のアプリのみをDockに表示
      - defaults write com.apple.dock static-only -bool true

  finder:
    desc: Change Finder Settings
    cmds:
      // ステータスバーを表示
      - defaults write com.apple.finder ShowStatusBar -bool true
      // パスバーを表示
      - defaults write com.apple.finder ShowPathbar -bool true
      // すべての拡張子のファイルを表示
      - defaults write NSGlobalDomain AppleShowAllExtensions -bool true
      // 隠しファイルを表示
      - defaults write com.apple.finder AppleShowAllFiles -bool true
      // 検索時にデフォルトでカレントディレクトリを検索
      - defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
      // Finderを再起動
      - killall Finder

  screenshot:
    desc: Change Screenshot Settings
    cmds:
      // スクリーンショット保存先を変更
      - defaults write com.apple.screencapture location ~/SCREENSHOTS
      // スクリーンショットファイル名
      - defaults write com.apple.screencapture name screenshot
      // スクリーンショットファイル名に日付を付けない
      - defaults write com.apple.screencapture include-date -bool false
      // フローティングサムネイルをスキップ
      - defaults write com.apple.screencapture show-thumbnail -bool false
