[tools]
python = "3.12"
deno = "latest"
node = "latest"
go = "latest"
yarn = "latest"
pnpm = "latest"
terraform = "latest"
usage = "latest"
# GitHub Actions用linter
actionlint = "latest"
zizmor = "latest"
yazi = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
fzf = "latest"
fd = "latest"
ffmpeg = "latest"
zoxide = "latest"


[settings]
idiomatic_version_file_enable_tools = ["python"]
