[tools]
# Languages
deno = "latest"
elixir = "latest"
erlang = "latest"
flutter = "latest"
go = "latest"
java = "latest"
julia = "latest"
node = "latest"
perl = "latest"
python = "3.12"
scala = "latest"
zig = "latest"
# CLI tools
bat = "latest"
biome = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
gping = "latest"
hub = "latest"
jq = "latest"
just = "latest"
lsd = "latest"
peco = "latest"
pnpm = "latest"
qsv = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
sd = "latest"
task = "latest"
terraform = "latest"
usage = "latest"
yarn = "latest"
yazi = "latest"
zoxide = "latest"
# GitHub Actions用linter
actionlint = "latest"
ghalint = "latest"
zizmor = "latest"


[settings]
idiomatic_version_file_enable_tools = ["python"]
